name: pypi

on:
  push:
    tags:
      - v*

jobs:
  build-n-publish:
    name: Build and publish Python packages to PyPI and TestPyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
          ref: ${{ github.event.release.target_commitish }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install setuptools and wheel
      run: >-
        python -m
        pip install
        setuptools wheel
        --user
    - name: Build a binary wheel and a source tarball
      run: >-
        python 
        setup.py
        sdist bdist_wheel
    - name: Publish Python package to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        repository_url: https://test.pypi.org/legacy/
        skip_existing: true
    - name: Publish Python package to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
